import { CAB_DEFAULT_COLOR } from './cabLayout'
import type { Approx, ChassisPresetInput } from './types'

/**
 * Standard chassis configurations from the manufacturers' published spec sheets.
 * Plain numbers are read from the cited source; a(…) marks an estimate (industry-typical value,
 * derived from a drawing of a sister model, or computed from other published values).
 * See docs/chassis-presets.md for the source list and what each estimate is based on.
 */
export const a = <T extends number | string | boolean>(value: T): Approx<T> => ({ value, approx: true })

const VOLVO_SHEET = (code: string) => `https://stpi.it.volvo.com/STPIFiles/Volvo/ModelRange/${code}_gbr_eng.pdf`
const VOLVO_BEP = 'public/samples/volvo-vssb-25-277591.dxf.gz (Volvo body builder order drawing VSSB-25-277591, FM 8x4)'
const SCANIA_FRAME =
  'https://bodybuilder.scania.com/content/dam/bodybuilder/tbb-files/taiwan/guide/Scania_NTG_Truck_chassis_construction_main_beam_and_subframe_2026.pdf'
const SCANIA_ICD = 'public/samples/scania-icd-sample.dxf (Scania ICD 2492101765219, G 360E B6x2*4NB)'
const SCANIA_R_TRACTOR = 'https://www.europa-lkw.de/technische-daten-modell/scania-la4x2mna'
const MAN_SHEET = (path: string) => `https://www.man-bodybuilder.co.uk/specs/pdf/2022/${path}.pdf`
const DAF_SHEET = (code: string) => `https://www.daf.co.uk/api/feature/specsheet/open?filename=TSGBEN016${code}202545.pdf`
const EU_LIMITS = 'https://eur-lex.europa.eu/eli/dir/1996/53/oj (Directive 96/53/EC, Annex I weights)'

const COLOR = CAB_DEFAULT_COLOR

export const PRESET_INPUTS: ChassisPresetInput[] = [
  // ───────────────────────────── VOLVO ─────────────────────────────
  {
    id: 'volvo-fh-4x2-tractor',
    make: 'volvo',
    series: 'FH',
    label: 'FH 4x2 tahač, spací kabina',
    wheelbases: [3500, 3600, 3700, 3800],
    wheelbaseRef: 'firstRear',
    source: VOLVO_SHEET('fh42t3a'),
    sources: [VOLVO_BEP],
    config: {
      make: 'volvo',
      series: 'FH',
      name: 'Volvo FH 4x2 tahač',
      kind: 'tractor',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 7500, track: a(2050), tyre: '315/80R22.5' },
        { position: 3700, steered: false, driven: true, lift: false, twin: true, maxLoad: 11500, track: a(1837), tyre: '315/80R22.5' },
      ],
      frontOverhang: 1365,
      rearOverhang: 1015,
      frame: { widthRear: a(852), widthFront: a(1080), taperEnd: a(360), sectionHeight: 266, flange: a(90), thickness: 8, topHeight: 1047, frontEnd: a(1120) },
      gvw: 18000,
      gcw: 40000,
      cab: { style: 'volvo', kind: 'sleeper', roof: 'normal', length: a(2372), height: 3504, width: 2500, backFromAxle: 1007, color: COLOR.volvo },
      fuel: { enabled: true, liters: 330, side: 'right' },
      adblue: { enabled: true, liters: 64, side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: true, lead: a(600), height: a(1270) },
      sideGuards: true,
      rearUnderrun: false,
      mudguards: true,
    },
  },
  {
    id: 'volvo-fh-6x2-tag-tractor',
    make: 'volvo',
    series: 'FH',
    label: 'FH 6x2 tahač s vlečenou nápravou',
    wheelbases: [3000, 3200, 3400, 3700, 3900],
    wheelbaseRef: 'firstRear',
    source: VOLVO_SHEET('fh62tt3a'),
    sources: [VOLVO_BEP],
    config: {
      make: 'volvo',
      series: 'FH',
      name: 'Volvo FH 6x2 tahač',
      kind: 'tractor',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 7500, track: a(2050), tyre: '315/80R22.5' },
        { position: 3400, steered: false, driven: true, lift: false, twin: true, maxLoad: a(11500), track: a(1837), tyre: '315/80R22.5' },
        { position: 4770, steered: a(true), driven: false, lift: true, twin: a(false), maxLoad: a(7500), track: a(2040), tyre: '315/80R22.5' },
      ],
      frontOverhang: 1365,
      rearOverhang: 995,
      frame: { widthRear: a(852), widthFront: a(1080), taperEnd: a(360), sectionHeight: 300, flange: a(90), thickness: a(8), topHeight: 1064, frontEnd: a(1120) },
      gvw: 26000,
      gcw: 44000,
      cab: { style: 'volvo', kind: 'sleeper', roof: 'normal', length: a(2372), height: 3507, width: 2500, backFromAxle: 1007, color: COLOR.volvo },
      fuel: { enabled: true, liters: 330, side: 'right' },
      adblue: { enabled: true, liters: 64, side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: true, lead: a(-200), height: a(1290) },
      sideGuards: true,
      rearUnderrun: false,
      mudguards: true,
    },
  },
  {
    id: 'volvo-fh-6x2-tag-rigid',
    make: 'volvo',
    series: 'FH',
    label: 'FH 6x2 podvozek s vlečenou nápravou',
    wheelbases: [3500, 3700, 3900, 4300, 4600, 4800, 4900, 5200, 5600, 6000],
    wheelbaseRef: 'firstRear',
    source: VOLVO_SHEET('fh62rt3a'),
    sources: [VOLVO_BEP],
    config: {
      make: 'volvo',
      series: 'FH',
      name: 'Volvo FH 6x2 podvozek',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 8000, track: a(2050), tyre: '315/80R22.5' },
        { position: 4900, steered: false, driven: true, lift: false, twin: true, maxLoad: a(11500), track: a(1837), tyre: '315/80R22.5' },
        { position: 6270, steered: true, driven: false, lift: true, twin: false, maxLoad: a(7500), track: a(2040), tyre: '315/80R22.5' },
      ],
      frontOverhang: 1365,
      rearOverhang: a(2400),
      frame: { widthRear: a(852), widthFront: a(1080), taperEnd: a(360), sectionHeight: 266, flange: a(90), thickness: 8, topHeight: 1046, frontEnd: a(1120) },
      gvw: 26000,
      gcw: a(0),
      cab: { style: 'volvo', kind: 'sleeper', roof: 'normal', length: a(2305), height: 3516, width: 2500, backFromAxle: 940, color: COLOR.volvo },
      fuel: { enabled: true, liters: 330, side: 'right' },
      adblue: { enabled: true, liters: 64, side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1250) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
  {
    id: 'volvo-fm-4x2-rigid',
    make: 'volvo',
    series: 'FM',
    label: 'FM 4x2 podvozek, denní kabina',
    wheelbases: [3400, 3700, 3800, 4000, 4300, 4600, 4900, 5200, 5600, 6000, 6300, 6700],
    wheelbaseRef: 'firstRear',
    source: VOLVO_SHEET('fm42r3a'),
    sources: [VOLVO_BEP],
    config: {
      make: 'volvo',
      series: 'FM',
      name: 'Volvo FM 4x2 podvozek',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 8000, track: a(2050), tyre: '315/80R22.5' },
        { position: 4900, steered: false, driven: true, lift: false, twin: true, maxLoad: 11500, track: a(1837), tyre: '315/80R22.5' },
      ],
      frontOverhang: a(1400),
      rearOverhang: a(2300),
      frame: { widthRear: a(852), widthFront: a(1080), taperEnd: a(360), sectionHeight: 266, flange: a(90), thickness: 7, topHeight: 1046, frontEnd: a(1155) },
      gvw: 18000,
      gcw: a(0),
      cab: { style: 'volvo', kind: 'day', roof: 'normal', length: a(1915), height: 3131, width: 2500, backFromAxle: 515, color: COLOR.volvo },
      fuel: { enabled: true, liters: 330, side: 'right' },
      adblue: { enabled: true, liters: 64, side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(3) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1250) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
  {
    id: 'volvo-fm-8x4-tridem',
    make: 'volvo',
    series: 'FMX',
    label: 'FMX 8x4 tridem (vlečená náprava), denní kabina',
    wheelbases: [3700, 3900, 4100, 4300, 4600, 4900, 5200],
    wheelbaseRef: 'firstRear',
    source: VOLVO_SHEET('fmx84rt3a'),
    sources: [VOLVO_BEP, EU_LIMITS],
    note: 'Zatížení tridemu 24 t je rozděleno na nápravy odhadem.',
    config: {
      make: 'volvo',
      series: 'FMX',
      name: 'Volvo FMX 8x4 tridem',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 8000, track: a(2080), tyre: '315/80R22.5' },
        { position: 4300, steered: false, driven: true, lift: false, twin: true, maxLoad: a(8500), track: 1837, tyre: '315/80R22.5' },
        { position: 5670, steered: false, driven: true, lift: false, twin: true, maxLoad: a(8500), track: 1837, tyre: '315/80R22.5' },
        { position: 7050, steered: true, driven: false, lift: true, twin: false, maxLoad: a(7000), track: a(2040), tyre: '315/80R22.5' },
      ],
      frontOverhang: 1520,
      rearOverhang: a(1300),
      frame: { widthRear: 852, widthFront: 1080, taperEnd: 360, sectionHeight: 300, flange: 90, thickness: 7, topHeight: 1064, frontEnd: 1275 },
      gvw: 32000,
      gcw: a(0),
      cab: { style: 'volvo', kind: 'day', roof: 'normal', length: a(2035), height: 3150, width: 2500, backFromAxle: 515, color: COLOR.volvo },
      fuel: { enabled: true, liters: 330, side: 'right' },
      adblue: { enabled: true, liters: 64, side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1250) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
  {
    id: 'volvo-fm-8x4-twinsteer',
    make: 'volvo',
    series: 'FMX',
    label: 'FM/FMX 8x4 dvě řízené přední nápravy (dle výkresu BEP)',
    wheelbases: [5100],
    wheelbaseRef: 'firstRear',
    source: VOLVO_BEP,
    sources: [EU_LIMITS],
    note: 'Rozměry z výkresu Volvo VSSB-25-277591; zatížení náprav jsou limity EU 96/53/ES.',
    config: {
      make: 'volvo',
      series: 'FMX',
      name: 'Volvo FM 8x4 twin-steer',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: a(7500), track: 2109, tyre: '385/65R22.5' },
        { position: 1995, steered: true, driven: false, lift: false, twin: false, maxLoad: a(7500), track: 2109, tyre: '385/65R22.5' },
        { position: 5100, steered: false, driven: true, lift: false, twin: true, maxLoad: a(9500), track: 1837, tyre: '315/80R22.5' },
        { position: 6470, steered: false, driven: true, lift: false, twin: true, maxLoad: a(9500), track: 1837, tyre: '315/80R22.5' },
      ],
      frontOverhang: 1520,
      rearOverhang: 1275,
      frame: { widthRear: 852, widthFront: 1080, taperEnd: 360, sectionHeight: 300, flange: 90, thickness: a(8), topHeight: 1064, frontEnd: 1275 },
      gvw: 32000,
      gcw: a(0),
      cab: { style: 'volvo', kind: 'day', roof: 'normal', length: 2417, height: a(3150), width: 2500, backFromAxle: 898, color: COLOR.volvo },
      fuel: { enabled: true, liters: a(330), side: 'right' },
      adblue: { enabled: true, liters: a(64), side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1250) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
  // ───────────────────────────── SCANIA ─────────────────────────────
  {
    id: 'scania-r-4x2-tractor',
    make: 'scania',
    series: 'R',
    label: 'R 4x2 tahač, kabina Highline',
    wheelbases: [3300, 3500, 3700, 3900],
    wheelbaseRef: 'firstRear',
    source: SCANIA_R_TRACTOR,
    sources: [SCANIA_FRAME, SCANIA_ICD],
    note: 'Sekundární zdroj (katalog europa-lkw.de, typ LA4x2MNA); rám dle Scania bodybuilder.',
    config: {
      make: 'scania',
      series: 'R',
      name: 'Scania R 4x2 tahač',
      kind: 'tractor',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 7500, track: a(2050), tyre: a('315/70R22.5') },
        { position: 3700, steered: false, driven: true, lift: false, twin: true, maxLoad: 13000, track: 1830, tyre: '315/70R22.5' },
      ],
      frontOverhang: 1460,
      rearOverhang: 775,
      frame: { widthRear: 768, widthFront: 1064, taperEnd: 1013, sectionHeight: 270, flange: 90, thickness: 8, topHeight: 1017, frontEnd: 1030 },
      gvw: 19000,
      gcw: a(40000),
      cab: { style: 'scania', kind: 'sleeper', roof: 'high', length: a(2250), height: 3940, width: 2495, backFromAxle: a(790), color: COLOR.scania },
      fuel: { enabled: true, liters: a(600), side: 'left' },
      adblue: { enabled: true, liters: a(80), side: 'left' },
      battery: { enabled: true, side: 'right' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: true, lead: 560, height: a(1250) },
      sideGuards: true,
      rearUnderrun: false,
      mudguards: true,
    },
  },
  {
    id: 'scania-r-6x2-rigid',
    make: 'scania',
    series: 'R',
    label: 'R 6x2*4 podvozek (rozměry dle ICD B6x2*4NB)',
    wheelbases: [4950],
    wheelbaseRef: 'firstRear',
    source: SCANIA_ICD,
    sources: [SCANIA_FRAME, EU_LIMITS, SCANIA_R_TRACTOR],
    note: 'Podvozek z výkresu ICD (G 360E B6x2*4NB) s kabinou R Normal; zatížení náprav jsou limity EU.',
    config: {
      make: 'scania',
      series: 'R',
      name: 'Scania R 6x2*4 podvozek',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: a(8000), track: 2117, tyre: '385/65R22.5' },
        { position: 4950, steered: false, driven: true, lift: false, twin: true, maxLoad: a(11500), track: 1830, tyre: '315/80R22.5' },
        { position: 6300, steered: true, driven: false, lift: true, twin: false, maxLoad: a(7500), track: 2091, tyre: '385/65R22.5' },
      ],
      frontOverhang: 1450,
      rearOverhang: 1960,
      frame: { widthRear: 768, widthFront: 1064, taperEnd: 1013, sectionHeight: 270, flange: 90, thickness: a(8), topHeight: 994, frontEnd: 1030 },
      gvw: a(26000),
      gcw: a(0),
      cab: { style: 'scania', kind: 'sleeper', roof: 'normal', length: a(2250), height: a(3600), width: 2495, backFromAxle: a(800), color: COLOR.scania },
      fuel: { enabled: true, liters: a(400), side: 'left' },
      adblue: { enabled: true, liters: a(80), side: 'left' },
      battery: { enabled: true, side: 'right' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1250) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
  {
    id: 'scania-g-6x2-rigid-icd',
    make: 'scania',
    series: 'G',
    label: 'G 360 B6x2*4NB podvozek (výkres ICD)',
    wheelbases: [4950],
    wheelbaseRef: 'firstRear',
    source: SCANIA_ICD,
    sources: [SCANIA_FRAME, EU_LIMITS],
    note: 'Všechny rozměry z výkresu ICD 2492101765219; zatížení náprav jsou limity EU.',
    config: {
      make: 'scania',
      series: 'G',
      name: 'Scania G 6x2*4 podvozek',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: a(8000), track: 2117, tyre: '385/65R22.5' },
        { position: 4950, steered: false, driven: true, lift: false, twin: true, maxLoad: a(11500), track: 1830, tyre: '315/80R22.5' },
        { position: 6300, steered: true, driven: false, lift: true, twin: false, maxLoad: a(7500), track: 2091, tyre: '385/65R22.5' },
      ],
      frontOverhang: 1450,
      rearOverhang: 1960,
      frame: { widthRear: 768, widthFront: 1064, taperEnd: 1013, sectionHeight: 270, flange: 90, thickness: a(8), topHeight: 994, frontEnd: 1030 },
      gvw: a(26000),
      gcw: a(0),
      cab: { style: 'scania', kind: 'day', roof: 'normal', length: 2202, height: 3048, width: a(2490), backFromAxle: 700, color: COLOR.scania },
      fuel: { enabled: true, liters: a(400), side: 'left' },
      adblue: { enabled: true, liters: a(60), side: 'left' },
      battery: { enabled: true, side: 'right' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1250) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
  {
    id: 'scania-s-4x2-tractor',
    make: 'scania',
    series: 'S',
    label: 'S 450 A4x2NA tahač, kabina CS20 High',
    wheelbases: [3750],
    wheelbaseRef: 'firstRear',
    source: 'Scania specification S 450 A4x2NA (via autoline listing); frame per Scania bodybuilder',
    sources: [SCANIA_FRAME, SCANIA_R_TRACTOR],
    config: {
      make: 'scania',
      series: 'S',
      name: 'Scania S 4x2 tahač',
      kind: 'tractor',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 7500, track: a(2050), tyre: '315/70R22.5' },
        { position: 3750, steered: false, driven: true, lift: false, twin: true, maxLoad: a(11500), track: a(1830), tyre: '315/70R22.5' },
      ],
      frontOverhang: a(1460),
      rearOverhang: a(775),
      frame: { widthRear: 768, widthFront: 1064, taperEnd: 1013, sectionHeight: 270, flange: 90, thickness: 8, topHeight: a(1017), frontEnd: a(1030) },
      gvw: a(18000),
      gcw: a(40000),
      cab: { style: 'scania', kind: 'sleeper', roof: 'high', length: a(2350), height: a(4000), width: 2550, backFromAxle: a(890), color: COLOR.scania },
      fuel: { enabled: true, liters: a(700), side: 'left' },
      adblue: { enabled: true, liters: a(80), side: 'left' },
      battery: { enabled: true, side: 'right' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: true, lead: 560, height: a(1250) },
      sideGuards: true,
      rearUnderrun: false,
      mudguards: true,
    },
  },
  // ───────────────────────────── MAN ─────────────────────────────
  {
    id: 'man-tgx-4x2-tractor',
    make: 'man',
    series: 'TGX',
    label: 'TGX 18.470 4x2 BLS tahač, kabina GN',
    wheelbases: [3600, 3900],
    wheelbaseRef: 'firstRear',
    source: MAN_SHEET('TGX/4x2-Tractor'),
    config: {
      make: 'man',
      series: 'TGX',
      name: 'MAN TGX 4x2 tahač',
      kind: 'tractor',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 7500, track: a(2040), tyre: '315/70R22.5' },
        { position: 3600, steered: false, driven: true, lift: false, twin: true, maxLoad: 11500, track: a(1810), tyre: '315/70R22.5' },
      ],
      frontOverhang: 1475,
      rearOverhang: 800,
      frame: { widthRear: 762, widthFront: 942, taperEnd: a(900), sectionHeight: 270, flange: 85, thickness: 8, topHeight: 965, frontEnd: a(1175) },
      gvw: 18000,
      gcw: 40000,
      cab: { style: 'man', kind: 'sleeper', roof: 'normal', length: a(2280), height: 3352, width: 2499, backFromAxle: 805, color: COLOR.man },
      fuel: { enabled: true, liters: 400, side: 'right' },
      adblue: { enabled: true, liters: 60, side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: true, lead: 585, height: 1253 },
      sideGuards: true,
      rearUnderrun: false,
      mudguards: true,
    },
  },
  {
    id: 'man-tgs-6x2-rigid',
    make: 'man',
    series: 'TGS',
    label: 'TGS 26 6x2-4 LL podvozek (řízená zvedací zadní)',
    wheelbases: [3900, 4200, 4500, 4800, 5100, 5500, 5900],
    wheelbaseRef: 'firstRear',
    source: MAN_SHEET('TGS/6x2-Rigid'),
    sources: [MAN_SHEET('TGX/6x2-Rigid'), MAN_SHEET('TGS/4x2-Rigid')],
    config: {
      make: 'man',
      series: 'TGS',
      name: 'MAN TGS 6x2 podvozek',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: a(8000), track: a(2040), tyre: '315/80R22.5' },
        { position: 4800, steered: false, driven: true, lift: false, twin: true, maxLoad: 11500, track: a(1810), tyre: '315/80R22.5' },
        { position: 6150, steered: true, driven: false, lift: true, twin: false, maxLoad: 7500, track: a(2040), tyre: '315/80R22.5' },
      ],
      frontOverhang: 1475,
      rearOverhang: a(2400),
      frame: { widthRear: 762, widthFront: 942, taperEnd: a(900), sectionHeight: 270, flange: 85, thickness: 8, topHeight: 980, frontEnd: a(1175) },
      gvw: 26000,
      gcw: a(0),
      cab: { style: 'man', kind: 'day', roof: 'normal', length: a(1965), height: 3123, width: 2499, backFromAxle: a(490), color: COLOR.man },
      fuel: { enabled: true, liters: a(400), side: 'right' },
      adblue: { enabled: true, liters: a(60), side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1250) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
  {
    id: 'man-tgs-6x4-tractor',
    make: 'man',
    series: 'TGS',
    label: 'TGS 33 6x4 BBS tahač',
    wheelbases: [3300, 3600, 3900],
    wheelbaseRef: 'firstRear',
    source: MAN_SHEET('TGS/6x4-Tractor'),
    config: {
      make: 'man',
      series: 'TGS',
      name: 'MAN TGS 6x4 tahač',
      kind: 'tractor',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: a(8000), track: a(2040), tyre: '315/80R22.5' },
        { position: 3300, steered: false, driven: true, lift: false, twin: true, maxLoad: 9500, track: a(1810), tyre: '315/80R22.5' },
        { position: 4700, steered: false, driven: true, lift: false, twin: true, maxLoad: 9500, track: a(1810), tyre: '315/80R22.5' },
      ],
      frontOverhang: 1475,
      rearOverhang: 700,
      frame: { widthRear: 762, widthFront: 942, taperEnd: a(900), sectionHeight: 270, flange: 85, thickness: 8, topHeight: 1061, frontEnd: a(1175) },
      gvw: 26000,
      gcw: a(44000),
      cab: { style: 'man', kind: 'sleeper', roof: 'normal', length: a(2280), height: 3112, width: 2499, backFromAxle: 805, color: COLOR.man },
      fuel: { enabled: true, liters: a(400), side: 'right' },
      adblue: { enabled: true, liters: a(60), side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: true, lead: a(500), height: 1370 },
      sideGuards: true,
      rearUnderrun: false,
      mudguards: true,
    },
  },
  {
    id: 'man-tgs-8x4-tipper',
    make: 'man',
    series: 'TGS',
    label: 'TGS 32 8x4 BB sklápěčový podvozek, kabina NN',
    wheelbases: [3205, 3505],
    wheelbaseRef: 'secondFrontToFirstRear',
    source: MAN_SHEET('TGS/8x4-Normal-Height-Tipper'),
    note: 'MAN udává rozvor od 2. přední nápravy k 1. zadní (L1).',
    config: {
      make: 'man',
      series: 'TGS',
      name: 'MAN TGS 8x4 sklápěč',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 7100, track: a(2040), tyre: '295/80R22.5' },
        { position: 1795, steered: true, driven: false, lift: false, twin: false, maxLoad: 7100, track: a(2040), tyre: '295/80R22.5' },
        { position: 5000, steered: false, driven: true, lift: false, twin: true, maxLoad: 9500, track: a(1810), tyre: '295/80R22.5' },
        { position: 6400, steered: false, driven: true, lift: false, twin: true, maxLoad: 9500, track: a(1810), tyre: '295/80R22.5' },
      ],
      frontOverhang: 1475,
      rearOverhang: 800,
      frame: { widthRear: 762, widthFront: 942, taperEnd: a(900), sectionHeight: 270, flange: 85, thickness: 7, topHeight: 1046, frontEnd: a(1175) },
      gvw: 32000,
      gcw: a(0),
      cab: { style: 'man', kind: 'day', roof: 'normal', length: a(1965), height: 3158, width: 2499, backFromAxle: 490, color: COLOR.man },
      fuel: { enabled: true, liters: 300, side: 'right' },
      adblue: { enabled: true, liters: a(60), side: 'right' },
      battery: { enabled: true, side: 'left' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1250) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
  // ───────────────────────────── DAF ─────────────────────────────
  {
    id: 'daf-xf-4x2-tractor',
    make: 'daf',
    series: 'XF',
    label: 'XF FT 4x2 tahač, spací kabina',
    wheelbases: [3250, 3600, 3800, 4000],
    wheelbaseRef: 'firstRear',
    source: DAF_SHEET('G0209AAAA'),
    config: {
      make: 'daf',
      series: 'XF',
      name: 'DAF XF FT 4x2 tahač',
      kind: 'tractor',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 8000, track: a(2050), tyre: '315/70R22.5' },
        { position: 3800, steered: false, driven: true, lift: false, twin: true, maxLoad: 11500, track: 1820, tyre: '315/70R22.5' },
      ],
      frontOverhang: 1530,
      rearOverhang: 990,
      frame: { widthRear: 790, widthFront: a(960), taperEnd: a(900), sectionHeight: 260, flange: a(80), thickness: a(7), topHeight: 970, frontEnd: a(1230) },
      gvw: 18000,
      gcw: 44000,
      cab: { style: 'daf', kind: 'sleeper', roof: 'high', length: 2360, height: a(3990), width: 2500, backFromAxle: 830, color: COLOR.daf },
      fuel: { enabled: true, liters: 620, side: 'left' },
      adblue: { enabled: true, liters: 80, side: 'left' },
      battery: { enabled: true, side: 'right' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: true, lead: 770, height: a(1220) },
      sideGuards: true,
      rearUnderrun: false,
      mudguards: true,
    },
  },
  {
    id: 'daf-xg-4x2-tractor',
    make: 'daf',
    series: 'XG',
    label: 'XG 450 FT 4x2 tahač',
    wheelbases: [4000],
    wheelbaseRef: 'firstRear',
    source: DAF_SHEET('G0309AAAA'),
    sources: [DAF_SHEET('G0209AAAA')],
    config: {
      make: 'daf',
      series: 'XG',
      name: 'DAF XG FT 4x2 tahač',
      kind: 'tractor',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 8000, track: a(2050), tyre: '315/70R22.5' },
        { position: 4000, steered: false, driven: true, lift: false, twin: true, maxLoad: 11500, track: 1820, tyre: '315/70R22.5' },
      ],
      frontOverhang: 1530,
      rearOverhang: 990,
      frame: { widthRear: 790, widthFront: a(960), taperEnd: a(900), sectionHeight: 260, flange: a(80), thickness: a(7), topHeight: 970, frontEnd: a(1230) },
      gvw: 18000,
      gcw: 44000,
      cab: { style: 'daf', kind: 'sleeper', roof: 'high', length: 2690, height: a(3990), width: 2500, backFromAxle: 1160, color: COLOR.daf },
      fuel: { enabled: true, liters: 765, side: 'left' },
      adblue: { enabled: true, liters: 85, side: 'left' },
      battery: { enabled: true, side: 'right' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: true, lead: 770, height: a(1220) },
      sideGuards: true,
      rearUnderrun: false,
      mudguards: true,
    },
  },
  {
    id: 'daf-xf-6x2-rigid',
    make: 'daf',
    series: 'XF',
    label: 'XF FAN 6x2 podvozek (řízená vlečená)',
    wheelbases: [3800, 4300, 4900, 5300, 5700, 6100],
    wheelbaseRef: 'rearCentre',
    source: DAF_SHEET('F0229NAAA'),
    note: 'Rozvor DAF je měřen ke středu zadní skupiny náprav.',
    config: {
      make: 'daf',
      series: 'XF',
      name: 'DAF XF FAN 6x2 podvozek',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 8000, track: a(2050), tyre: '315/70R22.5' },
        { position: 4200, steered: false, driven: true, lift: false, twin: true, maxLoad: a(11500), track: 1820, tyre: '315/70R22.5' },
        { position: 5600, steered: true, driven: false, lift: true, twin: false, maxLoad: a(7500), track: a(2040), tyre: '315/70R22.5' },
      ],
      frontOverhang: 1530,
      rearOverhang: a(1950),
      frame: { widthRear: 790, widthFront: a(960), taperEnd: a(900), sectionHeight: a(260), flange: a(80), thickness: a(7), topHeight: a(970), frontEnd: a(1230) },
      gvw: 26000,
      gcw: a(0),
      cab: { style: 'daf', kind: 'sleeper', roof: 'high', length: 2360, height: a(3990), width: 2500, backFromAxle: 830, color: COLOR.daf },
      fuel: { enabled: true, liters: a(430), side: 'left' },
      adblue: { enabled: true, liters: a(80), side: 'left' },
      battery: { enabled: true, side: 'right' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1220) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
  {
    id: 'daf-xd-8x4-twinsteer',
    make: 'daf',
    series: 'XD',
    label: 'XD 370 FAD 8x4 podvozek, denní kabina',
    wheelbases: [5050, 5300, 5700, 6400],
    wheelbaseRef: 'rearCentre',
    source: DAF_SHEET('F0171AAAA'),
    note: 'Rozvor DAF je měřen od 1. přední nápravy ke středu zadního tandemu.',
    config: {
      make: 'daf',
      series: 'XD',
      name: 'DAF XD FAD 8x4',
      kind: 'rigid',
      axles: [
        { position: 0, steered: true, driven: false, lift: false, twin: false, maxLoad: 8000, track: a(2050), tyre: a('315/80R22.5') },
        { position: 2050, steered: true, driven: false, lift: false, twin: false, maxLoad: 8000, track: a(2050), tyre: '315/80R22.5' },
        { position: 4600, steered: false, driven: true, lift: false, twin: true, maxLoad: 9500, track: 1820, tyre: '315/80R22.5' },
        { position: 6000, steered: false, driven: true, lift: false, twin: true, maxLoad: 9500, track: 1820, tyre: '315/80R22.5' },
      ],
      frontOverhang: 1530,
      rearOverhang: 1650,
      frame: { widthRear: 790, widthFront: a(960), taperEnd: a(900), sectionHeight: 310, flange: a(80), thickness: 6, topHeight: 1150, frontEnd: a(1230) },
      gvw: 32000,
      gcw: a(0),
      cab: { style: 'daf', kind: 'day', roof: 'normal', length: 2030, height: a(3300), width: 2500, backFromAxle: 500, color: COLOR.daf },
      fuel: { enabled: true, liters: 340, side: 'left' },
      adblue: { enabled: true, liters: 45, side: 'left' },
      battery: { enabled: true, side: 'right' },
      airTanks: { enabled: true, count: a(4) },
      exhaust: { kind: 'horizontal', side: 'right' },
      fifthWheel: { enabled: false, lead: 0, height: a(1250) },
      sideGuards: true,
      rearUnderrun: true,
      mudguards: true,
    },
  },
]
