import type { Profile } from './types'

/**
 * Volvo chassis drawing exported from Volvo Order Information (BEP).
 * Views are block-name suffixes, not layers. Verified on VSSB-25-277591
 * (FM cab, 8x4, axles at 2982 / 4976 / 8082 / 9452).
 */
export const volvoBepProfile: Profile = {
  id: 'volvo-bep',
  version: 1,
  manufacturer: 'Volvo',
  name: 'Volvo podvozek (Order Information / BEP)',
  detect: {
    texts: [
      { regex: 'Generated by Volvo Order Information', weight: 5 },
      { regex: 'vbi\\.truck\\.volvo\\.com', weight: 3 },
      { regex: 'Bodywork exchange parameters \\(BEP\\)', weight: 2 },
      { regex: 'FO Number / OM Number:', weight: 2 },
    ],
    layers: [
      { regex: '^\\d{2}_(Frame|Cab|Front_wheels|Rear_wheels|Dimensions|Crossmember)$', minMatches: 4, weight: 3 },
      { regex: '^(50|51|60|61)_Holes_', minMatches: 2, weight: 2 },
    ],
    blocks: [
      { regex: '^B_VSSB_.+_DWG_INFO$', weight: 3 },
      { regex: '^B_[A-Z]{2,3}_\\d{7,8}', minMatches: 40, weight: 2 },
    ],
    minScore: 7,
  },
  ignore: { blocks: [], layers: ['Defpoints', '3', '8'], blockPatterns: ['^\\*D\\d+$'] },
  views: {
    side: ['01_Cab', '02_Frame', '06_*', '07_*', '13_*', '17_*'],
    top: ['01_Cab', '02_Frame', '06_*', '07_*', '13_*', '17_*'],
    cab: ['01_Cab', '13_*', '14_*'],
    holesLeft: ['50_*'],
    holesRight: ['51_*'],
    dimensions: ['09_Dimensions'],
    info: [],
    frameSide: ['02_Frame'],
    frameTop: ['02_Frame'],
    crossmembers: ['17_*'],
  },
  blockViews: {
    special: [
      { regex: '^FAI_TYRES_TOPVIEW$', view: 'top' },
      { regex: '^RAI_TYRES_TOPVIEW$', view: 'top' },
      { regex: '^FAI_TYRES_FRONTVIEW$', view: 'front' },
      { regex: '^B_RIM_DISC_WHEEL_.*SV$', view: 'side' },
      { regex: '^B_FE_TAG_RIG_HT$', view: 'top' },
      { regex: '^B_FE_TAG_RIG_HTSVL$', view: 'side' },
    ],
    cab: { regex: '^B_CAB([STF])C', map: { S: 'side', T: 'top', F: 'front' } },
    part: {
      regex: '^B_[A-Z]{2,3}_\\d{7,8}[A-Z0-9]*?(SVL|SVR|SV|FV|R)?$',
      viewGroup: 1,
      defaultView: 'top',
      map: { SV: 'side', SVL: 'side', SVR: 'side', FV: 'front', R: 'rear' },
    },
  },
  holeFrame: {
    layers: ['50_*', '51_*', '60_*', '61_*'],
    name: '^B_HG_\\d+$',
    reference: '^B_CABSC0_',
    fallback: { scale: 10, x: -58.5, y: 10856.25 },
  },
  curveTolerance: 2,
  dimensionLabels: {
    pattern: '([LHW]\\d{3}(?:\\.[A-Z0-9]+)*)\\s*=\\s*(-?[\\d.,]+)',
    maxGap: 400,
  },
  componentPattern: '^B_(?<cat>[A-Z]{2,3})_(?<pn>\\d{7,8})',
  componentSkip: ['^B_(FA|RA|XM|CM|FI|BI|HG)_', '^B_RIM_', '^FAI_', '^RAI_', '^B_CAB'],
  axleInserts: {
    name: '^B_RIM_DISC_WHEEL_.*SV$',
    frontLayers: ['06_*'],
    rearLayers: ['07_*'],
  },
  tireText: '\\d{3}/\\d{2}R\\d{2}(?:\\.\\d)?',
  innerLiner: {
    start: 'INNER LINER START\\s*=\\s*(-?\\d+)',
    stop: 'INNER LINER STOP\\s*=\\s*(-?\\d+)',
    axle: 2,
    startSign: -1,
    stopSign: 1,
  },
  sectionLayer: '02_Frame',
  semantics: {
    wheelbase: 'L011',
    wheelbaseAxles: [0, 2],
    axleSpacings: ['L012.1', 'L012.2', 'L012.3'],
    theoreticalWheelbase: 'L015',
    frontOverhang: 'L016',
    frameFrontOverhang: 'L018',
    rearOverhang: 'L019',
    frameOuterWidth: 'W036',
    frameOuterWidthFront: 'W035',
    flangeWidth: 'W032',
    frameHeight: 'H032',
    frameTopFrontLaden: 'H036',
    frameTopFrontUnladen: 'H035',
    frameTopRearLaden: 'H038',
    frameTopRearUnladen: 'H037',
    tracks: ['W013.1', 'W013.1', 'W013.2', 'W013.2'],
  },
}
